services:
  backend:
    build: ./backend
    container_name: movie_backend
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media:ro
      - ./backend/app:/app/app
    environment:
      - MOVIES_PATH=/app/media/movies
      - SERIES_PATH=/app/media/series
      - CORS_ORIGINS=http://localhost,http://192.168.1.215
    restart: unless-stopped
    networks:
      - movie_network

  frontend:
    build: ./frontend
    container_name: movie_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - movie_network

networks:
  movie_network:
    driver: bridge
